mqtt:
  enabled: false
detectors:
  onnx:
    type: onnx
model:
  model_type: yolo-generic
  width: 320
  height: 320
  input_tensor: nchw
  input_dtype: float
  path: /config/model_cache/yolov9-s-320.onnx
  labelmap_path: /labelmap/coco-80.txt
ffmpeg:
  hwaccel_args: preset-nvidia
genai:
  nitro_ollama:
    provider: ollama
    base_url: http://host.docker.internal:11434
    model: qwen3-vl:4b
    roles:
      - descriptions
    provider_options:
      keep_alive: -1
      options:
        num_ctx: 8192
go2rtc:
  streams:
    testcam:
      - ffmpeg:virtual?video&size=1280x720#video=h264
    phone:
      - ffmpeg:http://10.1.10.75:8080/video#video=h264
cameras:
  testcam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/testcam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      continuous:
        days: 1
  phone:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/phone
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
      genai:
        enabled: true
        use_snapshot: true
        objects:
          - person
    record:
      enabled: true
      continuous:
        days: 1
    snapshots:
      enabled: true
version: 0.18-0